### ISSUE TITLE
Podio Service

### ISSUE THREAD

**Issue by davidpestana** [Singularu/services#1]
Build a basic podio client service to connect with Podio API...

**Comment by nestorsng** [comment]
@davidpestana te dejo aquí documentación:

- API Podio
https://developers.podio.com

- Podio Singularu
https://podio.com/singularucom

**Comment by nestorsng** [comment]
Nomenclatura para nombres de los LOTES/PLANCHAS:
-Cuando sea personalización "corte" (NO infinito)  **AAMMDD_YC0001**
-Cuando sea personalización corte "infinito" **AAMMDD_YI0001**
-Cuando sea personalización grabado "dream"  **AAMMDD_VD0001**
-Cuando sea personalización grabado "moon"  **AAMMDD_VM0001**
-Cuando sea personalización grabado "plate"  **AAMMDD_VP0001**

*AAMMDD es la fecha actual en ese formato.
**El número al final del nombre corresponde con el número de placa generada en el día (se resetea todos los días).

**Comment by nestorsng** [comment]
Número máximo de "customisations" por cada "lot":
- "corte" (NO infinito): ??
- corte "infinito": 8
- grabado "dream": 25
- grabado "moon": 36
- grabado "plate": ??

**Comment by davidpestana** [comment]
los interrogantes significan que aun no lo sabemos? o que no hay limite?

**Comment by nestorsng** [comment]
Perdona, que no lo indiqué.
Todavía no me lo han sabido decir, pero bueno como dijimos que esto sería un parámetro más, será cambiarlo cuando lo sepamos y ya está, no?

Néstor Rodríguez Ibáñez
nestor@singularu.com
www.singularu.com

**Comment by davidpestana** [comment]
correcto ... este es el actuar parameters

    podio_auth:
        client_id: singularu
        client_secret: QmaeJhHxxx
    podio_conf:
        corte_finito:  10
        corte_infinito: 8
        grabado_dream: 25
        grabado_moon: 36
        grabado_plate: 10
    podio_apps:
        lot:
            app_id: 19787387
            app_token: 366c076320xx
        customisation:
            app_id: 19787411
            app_token: 0e8a3241d82xx

**Comment by nestorsng** [comment]
Política de nombres para las "customisations"=número de pedido (#54231) que se obtiene de los datos del pedido. 
*con almohadilla delante

**Comment by nestorsng** [comment]
Estados disponibles en "lots":

- Abierto: estado por defecto cuando se crea un lot nuevo.
- Completo: cuando no le caben más customisations.
- Diseñador: cuando se le asigna un lot aun diseñador (user).
- Plancha: diseño acabado.
- Máquina: lot en producción (cortar o grabar).
- Cerrado: lot cortado/grabado. Se cierra ciclo.


Estados disponibles en "customisation":

- Sin asignar: estado por defecto cuando se crea una customisation
- Asignado: cuando se asigna a un lot
- Diseñador: cuando se asigna a un diseñador
- Plancha: cuando se ha terminado su diseño
- Máquina: cuando está en producción (corte/grabado)
- Taller: cuando está en taller
- Recepcionado: cuando se recibe desde el taller
- Enviado: cuando se envía al cliente final
- Inicidencia: en cualquier momento que ocurra una incidencia en el proceso de esta customisation (proceso manual).

**Comment by davidpestana** [comment]
Podio Service Entregado y operativo...

clase autonoma sin interdependencias que resuelve toda la logica de negocio de podio
