### ISSUE TITLE
Check webhook data received

### ISSUE THREAD

**Issue by nestorsng** [Singularu/services#10]
No se están volcando los datos recibidos del segundo shopify.
Checked:
- URL webhook comprobada, es igual que la indicada en el primer shopify
- No puede ser fallo de verificación porque no se está comprobando la firma del webhook.

**Comment by davidpestana** [comment]
puedes probar de nuevo... la nueva version controla los nombres con # que llegan desde el segundo shopify, y ya no se generan excepciones por sku de stock... por lo que sera mas facil segregar las peticiones del log y asegurarnos de si el segundo shopify realmente emite datos al service-

**Comment by nestorsng** [comment]
Están los dos webhooks activos. 
Iremos viendo los pedidos que entren hoy de personalizado en ambos sitios para ver si los datos recibidos son correctos y cerramos issue.

**Comment by davidpestana** [comment]
Hemos comprobado que los de la tienda fisica no llegan debido a la politica de notacion de personalizaciones....  que ya esta en la issue #11
