### ISSUE TITLE
Casuística productos personalizados Tienda física

### ISSUE THREAD

**Issue by nestorsng** [Singularu/services#11]
Cuando entre un pedido de producto personalizado en el segundo Shopify (tienda física) deberá seguirse el siguiente procedimiento:

1. Detectaremos que la llamada viene de este Shopify concreto por el dato que nos manda el propio Shopify en las cabeceras:
- HTTP_X_SHOPIFY_SHOP_DOMAIN => 'possingularu.myshopify.com'

1. La dirección destino -y cualquier otro dato que falte- habrá que asignar los datos de Singularu:
Singularu
Calle Conde Salvatierra 33
46004 Valencia
Valencia (España)
Tlf: 960 882 867
Email: tienda@singularu.com

2. La o las personalizaciones para este caso, vienen en el campo "note" del pedido y siguen las siguientes normas: 

- por cada producto en el 'order' debe haber una linea en el campo "note", tanto si es personalizado como si no.

- cada una de estas lineas llevara el orden implícito en la forma:
1# 
2#
3#
...

- Si el producto en cuestión NO es personalizado, la linea deberá escribirse igualmente e ira vacía con tan solo el '1#'

- Si el producto en cuestión SI es personalizado, la linea contendrá el número de linea y SIN ESPACIOS la personalización en la forma: 2#personalización

- Si el producto personalizado en cuestión lleva más de una personalización, estas iran separadas por '|' en la forma 3#perso1|perso2|perso3

Por ejemplo, el pedido (real) "ESP4601#3-2378" en la tienda física, consta de 2 unidades de producto personalizados (Collar Personalizado Sue Plata). Sus respectivas personalizaciones vienen de la forma: 
> 1#Andrea
> 2#Sara

El pedido ESP4601#4-2119 consta de 2 unidades de "Collar Infinito 2 Nombres Plata" (dos personalizaciones por joya). Sus respectivas personalizaciones vienen de la forma:

> 1#Sol|Coral||Maruja|Coral

En el caso de un pedido con varios productos personalizados diferentes (orden en el pedido: 1º. Collar Personalizado Sue Plata + 2º. Collar Infinito 2 Nombres Plata) las personalizaciones vendrían de la siguiente forma:

> 1#Amparo
> 2#Jose|Toni 

En el caso de que un pedido lleve varias unidades de algún producto personalizado, el orden en el campo "note" deberá ser el mismo que en el pedido contando cada unidad del personalizado como única e individual. Pedido con 4 unidades de Collar personalizado, 1 unidad de producto de stock y 1 unidad de pulsera personalizable (en ese orden):

> 1#perso||perso||perso||perso
> 2#
> 3#perso

**Comment by davidpestana** [comment]
Aplicar el DefaultCustomerInfo... no se resuelve en funcion del header HTTP_X_SHOPIFY_SHOP_DOMAIN

si no directamente de si existe informacion en el shipping address

`        if(!isset($data->shipping_address)) return $this->getDefaultCustomerInfo($email);
`
