### ISSUE TITLE
ShopifyBundle

### ISSUE THREAD

**Issue by davidpestana** [Singularu/services#2]
create a shopify bundle to listen a shopify webhook calls

**Comment by nestorsng** [comment]
Documentación API Shopify & Webhooks:
- https://help.shopify.com/api/reference
- https://help.shopify.com/api/reference/webhook
- https://help.shopify.com/api/getting-started/webhooks
*los webhooks se configuran desde el back del Shopify, si lo necesitas puedo darte de alta el que me indiques.

Te dejo también enlaces que te pueden ser de utilidad:
- https://github.com/phpish/shopify_app-skeleton
- https://github.com/ShopifyExtras/PHP-Shopify-API-Wrapper
- https://github.com/Shopify/shopify_theme

**Comment by nestorsng** [comment]
Lógica para diferenciar los diferentes tipos de productos personalizados:

- Todas las comprobaciones las haremos en base al "SKU" del producto. Este se puede encontrar entre los "line_items" de un "order" (datos recibidos desde el webhook de shopify).
La estructura de un SKU: **YCOIN2N925A00XX**
- posición 1: **Y** = indica si es corte o grabado (**Y** corte, **V** grabado, **Z** resto)
- posiciones 2 y 3: **CO**=indican el tipo de joya (**CO**llar, **PU**lsera, **PE**ndientes...)
- posiciones 4, 5, 6 y 7: **IN2N**=indican el modelo (en este caso **IN**finito **2N**ombres)
- posiciones 8, 9, 10 y 11: **925A**=indican el material y color (925P Plata, 925A Oro Amarillo, - 925R Oro Rosa, 750A Oro Amarillo 18K)
- posiciones 12 y 13: **00**=tipo de piedra preciosa si corresponde
- posiciones 14 y 15: **XX**=indica la talla si corresponde

- Primero deberemos comprobar si es corte, grabado u otro checkeando la primera letra del SKU
Si es corte (**Y**) hay que comprobar si es INFINITO o resto. Para comprobar si es infinito debemos checkear las posiciones 4 y 5 del SKU, si el valor es **IN** es INFINITO, sino resto.
Si es grabado (**V**) hay que comprobar si es de tipo plate, moon o dream checkeando las posiciones 6 y 7: si son "**MO**" es de tipo MOON, si son "**PL**" son de tipo PLATE y si no son de ninguna de las anteriores es de tipo DREAM.

**Comment by davidpestana** [comment]
Bundle de endpoints y operaciones para shopify
