### ISSUE TITLE
platform.sh_deploy

### ISSUE THREAD

**Issue by nestorsng** [Singularu/services#3]
Datos acceso "platform.sh" para hacer deploy del project:
USR: nexxx@singxxxx.com
PWD: ----------

**Comment by davidpestana** [comment]
has deployado o necesitas que lo haga yo?

2017-11-06 11:00 GMT+01:00 Néstor Rodríguez <notifications@github.com>:

**Comment by davidpestana** [comment]
deploy continuo funcionando
