### ISSUE TITLE
Podio item "Personalización" update

### ISSUE THREAD

**Issue by nestorsng** [Singularu/services#5]
Hay que añadir más campos a las "customisation" porque en un paso posterior los necesitamos para generar un archivo. Los campos a añadir son:

- Cantidad -> "line_items": [ { "quantity"
- Nombre dest - > “shipping_address”: { “first_name” + “shipping_address”: { “last_name”
- Teléfono dest -> “shipping_address”: { “phone”
- Ciudad dest -> “shipping_address”: { “city”
- Código Postal -> “shipping_address”: { “zip”
- Provincia dest (una letra “V”=Valencia) -> “shipping_address”: { “province”
- Dirección dest -> { “email”
- Email dest -> “shipping_address”: { “
- Paquetes -> SIEMPRE VALOR 1
- Reembolso -> SIEMPRE VALOR 0,00
- Kilos -> SIEMPRE VALOR  1
- Con Acuse -> SIEMPRE VALOR N
- Con Retorno -> SIEMPRE VALOR N
- Código Cliente -> SIEMPRE VALOR 02597
- Porte -> SIEMPRE VALOR  P
- Servicio -> SIEMPRE VALOR 24
- Sábado -> SIEMPRE VALOR N

*Ya están añadidos en Podio
**Los campos que pone "SIEMPRE VALOR" deberán llevar siempre los valores indicados (podríamos ponerlos como parameters por si se modifican en un futuro ya que cabe la posibilidad de que si ocurra)

**Comment by davidpestana** [comment]
Todos los campos siempre valor los quieres como parametros?...
no haría excesivo el "parameters"?

en cada customisation el quantity es el numero de line_items totales? ... ( es ilogico no ? )

**Comment by nestorsng** [comment]
Los campos SIEMPRE VALOR te lo decía porque siempre van a llevar el mismo valor, salvo que cambiemos de servicio o empecemos a enviar al extranjero. Pero si consideras que hardcoded estará mejor, no hay problema.

En cuanto a la quantity es la cantidad de cada line_item, por si de un mismo producto se han comprado más de una unidad, NO la cantidad total de productos que lleva el order.
