### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by nestorsng** [Singularu/services#6]
set up error logs and error notification

**Comment by davidpestana** [comment]
la cuenta de gmail que se use para configurar el swift mailer 

debe tener activo el check 
'permitir aplicaciones menos seguras' en esta url https://myaccount.google.com/security?hl=es#connectedapps

![captura de pantalla de 2017-12-06 07-54-36](https://user-images.githubusercontent.com/5878617/33648574-e0729364-da5a-11e7-87b0-127d1e4ed865.png)
