### ISSUE TITLE
customisation field "ID pedido"

### ISSUE THREAD

**Issue by nestorsng** [Singularu/services#8]
Cuando un pedido lleva más de un producto "personalizado" (customisation), el campo "ID pedido" debe añadir al final ".1" en base a la cantidad. 

Por ejemplo si hay 3 productos llevarán respectivamente ".1", ".2" y ".3"

**Comment by nestorsng** [comment]
Los pedidos que vienen del segundo Shopify llevan un ID diferente: **ESP4601#3-1714**
Descartamos, por el momento, la información hasta la '#', por lo que el número de pedido quedaría de la forma: **#3-1714**

**Comment by davidpestana** [comment]
Solved
