### ISSUE TITLE
Casuística SKU

### ISSUE THREAD

**Issue by nestorsng** [Singularu/services#9]
Posibles casos cuando recibimos un order desde shopify:
_*estos son los que he visto que faltaban, el resto están correctos._

ProductType:
case "Y" = corte
case "V" = grabado
case "Z" = stock
case "W" = stockSingularu

Typology
case "CO" = "collar"
case "PU" = "pulsera"
case "PE" = "pendientes"
case "AN" = "anillo"
case "TO" = "tobilleras"

**Comment by davidpestana** [comment]
@nestorsng  

Si el product Type es StockSingularu...  no agrego a Podio la customisation.

Pero si es Tobillera si?

**Comment by nestorsng** [comment]
No, si es tobillera lleva delante la letra "Z" por lo que es stock y no debe agregarse al podio. :)
